[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test/contracts'
cache_path = 'cache_forge'
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/',
    'contracts/=contracts/'
]

[rpc_endpoints]
localhost = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
